services:
  api:
    image: <user name>/<image name> # Use the custom Docker image
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
      - JWT_SECRET=${JWT_SECRET}
    command: sh -c "npm run prisma:migrate && npm run prisma:generate && npm run start"
    expose:
      - 3000
